tp1: main.c lista.c lista.h fila.c fila.h heap.c heap.h
	gcc -Wall -g -o tp1 main.c lista.c fila.c heap.c
	#valgrind 
	./tp1 < inputs/input.txt

val:
	valgrind ./tp1 < inputs/input.txt

clean:
	rm tp1
